# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pirelay.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pirelay.proto',
  package='pirelay',
  syntax='proto3',
  serialized_pb=_b('\n\rpirelay.proto\x12\x07pirelay\"!\n\x0ePiRelayChannel\x12\x0f\n\x07\x63hannel\x18\x01 \x01(\r\"1\n\x0ePiRelaysAnswer\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\x86\x01\n\x07PiRelay\x12<\n\x06\x45nable\x12\x17.pirelay.PiRelayChannel\x1a\x17.pirelay.PiRelaysAnswer\"\x00\x12=\n\x07\x44isable\x12\x17.pirelay.PiRelayChannel\x1a\x17.pirelay.PiRelaysAnswer\"\x00\x42(\n\x10\x63\x61t.ifae.pirelayB\x0cPiRelayProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_PIRELAYCHANNEL = _descriptor.Descriptor(
  name='PiRelayChannel',
  full_name='pirelay.PiRelayChannel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel', full_name='pirelay.PiRelayChannel.channel', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=59,
)


_PIRELAYSANSWER = _descriptor.Descriptor(
  name='PiRelaysAnswer',
  full_name='pirelay.PiRelaysAnswer',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='answer', full_name='pirelay.PiRelaysAnswer.answer', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='pirelay.PiRelaysAnswer.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=61,
  serialized_end=110,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='pirelay.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['PiRelayChannel'] = _PIRELAYCHANNEL
DESCRIPTOR.message_types_by_name['PiRelaysAnswer'] = _PIRELAYSANSWER
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PiRelayChannel = _reflection.GeneratedProtocolMessageType('PiRelayChannel', (_message.Message,), dict(
  DESCRIPTOR = _PIRELAYCHANNEL,
  __module__ = 'pirelay_pb2'
  # @@protoc_insertion_point(class_scope:pirelay.PiRelayChannel)
  ))
_sym_db.RegisterMessage(PiRelayChannel)

PiRelaysAnswer = _reflection.GeneratedProtocolMessageType('PiRelaysAnswer', (_message.Message,), dict(
  DESCRIPTOR = _PIRELAYSANSWER,
  __module__ = 'pirelay_pb2'
  # @@protoc_insertion_point(class_scope:pirelay.PiRelaysAnswer)
  ))
_sym_db.RegisterMessage(PiRelaysAnswer)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'pirelay_pb2'
  # @@protoc_insertion_point(class_scope:pirelay.Empty)
  ))
_sym_db.RegisterMessage(Empty)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\020cat.ifae.pirelayB\014PiRelayProtoP\001\242\002\003HLW'))
try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PiRelayStub(object):
    """The greeting service definition.
    """

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.Enable = channel.unary_unary(
          '/pirelay.PiRelay/Enable',
          request_serializer=PiRelayChannel.SerializeToString,
          response_deserializer=PiRelaysAnswer.FromString,
          )
      self.Disable = channel.unary_unary(
          '/pirelay.PiRelay/Disable',
          request_serializer=PiRelayChannel.SerializeToString,
          response_deserializer=PiRelaysAnswer.FromString,
          )


  class PiRelayServicer(object):
    """The greeting service definition.
    """

    def Enable(self, request, context):
      """Sends a greeting
      """
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def Disable(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PiRelayServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'Enable': grpc.unary_unary_rpc_method_handler(
            servicer.Enable,
            request_deserializer=PiRelayChannel.FromString,
            response_serializer=PiRelaysAnswer.SerializeToString,
        ),
        'Disable': grpc.unary_unary_rpc_method_handler(
            servicer.Disable,
            request_deserializer=PiRelayChannel.FromString,
            response_serializer=PiRelaysAnswer.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'pirelay.PiRelay', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPiRelayServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def Enable(self, request, context):
      """Sends a greeting
      """
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def Disable(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPiRelayStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    """The greeting service definition.
    """
    def Enable(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      """Sends a greeting
      """
      raise NotImplementedError()
    Enable.future = None
    def Disable(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    Disable.future = None


  def beta_create_PiRelay_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('pirelay.PiRelay', 'Disable'): PiRelayChannel.FromString,
      ('pirelay.PiRelay', 'Enable'): PiRelayChannel.FromString,
    }
    response_serializers = {
      ('pirelay.PiRelay', 'Disable'): PiRelaysAnswer.SerializeToString,
      ('pirelay.PiRelay', 'Enable'): PiRelaysAnswer.SerializeToString,
    }
    method_implementations = {
      ('pirelay.PiRelay', 'Disable'): face_utilities.unary_unary_inline(servicer.Disable),
      ('pirelay.PiRelay', 'Enable'): face_utilities.unary_unary_inline(servicer.Enable),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_PiRelay_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('pirelay.PiRelay', 'Disable'): PiRelayChannel.SerializeToString,
      ('pirelay.PiRelay', 'Enable'): PiRelayChannel.SerializeToString,
    }
    response_deserializers = {
      ('pirelay.PiRelay', 'Disable'): PiRelaysAnswer.FromString,
      ('pirelay.PiRelay', 'Enable'): PiRelaysAnswer.FromString,
    }
    cardinalities = {
      'Disable': cardinality.Cardinality.UNARY_UNARY,
      'Enable': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'pirelay.PiRelay', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
